In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn import datasets

In [9]:
data = datasets.load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

In [10]:
x =  data.data 
y = data.target
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

classifier = KNeighborsClassifier(n_neighbors=5) 
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)

print('Confusion Matrix')                                                                                             
print(confusion_matrix(y_test,y_pred))
print('Accuracy Metrics') 
print(classification_report(y_test,y_pred))

Confusion Matrix
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Accuracy Metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [11]:
from sklearn.neighbors import RadiusNeighborsClassifier
rnc = RadiusNeighborsClassifier(radius = 5)
rnc.fit(x_train, y_train)

classes = {0:'setosa',1:'versicolor',2:'virginicia'}
x_new = [[1,1,1,1],[4,3,1.3,0.2]]
y_predict = rnc.predict(x_new)
print(classes[y_predict[0]])
print(classes[y_predict[1]])

setosa
versicolor


In [29]:
from scipy import stats

In [30]:
def EuclideanDistance(x1, x2):
    return np.sum((x1 - x2) ** 2, axis=1)

In [31]:
class KNN:
    def __init__(self, k, distance_metric=EuclideanDistance, task_type='Classification'):
        self._k = k
        self._distance_metric = distance_metric
        self._task_type = task_type
    def fit(self, X, y):
        self._X = X
        self._y = y
    def predict(self, newExample):
        distance_vector = self._distance_metric(self._X, newExample)
        k_nearest_neighbors_indices = np.argpartition(distance_vector, self._k)[:self._k]
        k_nearest_neighbors = self._y[k_nearest_neighbors_indices]
        if self._task_type == 'Classification':
            label = stats.mode(k_nearest_neighbors)[0]
        else:
            label = k_nearest_neighbors.mean()
        return label, k_nearest_neighbors_indices
    def eval(self, X_test, y_test):
        y_pred = np.zeros(y_test.shape)
        for i in range(y_test.shape[0]):
            y_predicted[i], _ = self.predict(X_test[i,:])
        if self._task_type == 'Classification': # for all examples
            error = np.mean(y_test == y_pred, axis=0)
        else:
            error_vector = y_predicted - y_test
            error = np.sqrt((error_vector.T @ error_vector) / error_vector.ravel().shape[0])
        return error

In [32]:
pred = KNN(k=5)
pred.fit(X_train,y_train)

In [33]:
pred.predict(X_test[0])

(array([1], dtype=int64), array([ 67, 263, 538, 276, 490], dtype=int64))

In [34]:
y_test[0]

1